version: "3"

services:
        order:
                build: ./Order
                ports:
                        - "80:80"
                volumes:
                        - ./:/HotBurger
        monitor:
                build: ./Monitor
                ports:
                        - "8080:8080"
                volumes:
                        - ./:/HotBurger
        inventory:
                build: ./Inventory
                ports:
                        - "8082:8082"
        customerservice:
                build: ./CustomerService
